config/routes.rb
WeddingInvite::Application.routes.draw do
  get 'out_of_towners' => 'out_of_towners#info', :as => :out_of_towners
  get 'gifts' => 'gifts#info', :as => :gifts
  get 'rsvp' => 'rsvp#details', :as => :rsvp
  get 'rsvp/send' => 'rsvp#create', :as => :send_rsvp, :via => :post
  get 'ceremony_and_reception' => 'ceremony_and_reception#info', :as => :ceremony_and_reception
  get 'admin' => 'admin#list', :as => :admin_path

  root :to => 'home#index', :as => :home

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  attr_accessor :address, :email, :name, :number, :status
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ceremony_and_reception_controller.rb
class CeremonyAndReceptionController < ApplicationController
  def info
    @title = 'Ceremony And Reception'
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def info
    @title = 'Gifts'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = 'Home'
  end
end

app/controllers/out_of_towners_controller.rb
class OutOfTownersController < ApplicationController
  def info
  end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  def details
    @title = 'RSVP'
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new(:name => params[:rsvp][:name],
                     :number => params[:rsvp][:number],
                     :email => params[:rsvp][:email],
                     :address => params[:rsvp][:address],
                     :status => params[:rsvp][:status])
    if @rsvp.save 
      Notifications.notify_rsvp(@rsvp).deliver
    else
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ceremony_and_reception_helper.rb
module CeremonyAndReceptionHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/out_of_towners_helper.rb
module OutOfTownersHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/list.html.erb
<h1>RSVP Details</h1>
<ul>
  <% Rsvp.all.each do |rsvp| %>
  <li>
  <p>Name: <%= rsvp.name %></p>
  <p>Number: <%= rsvp.number %></p>
  <p>Email: <%= rsvp.email %></p>
  <p>Address: <%= rsvp.address %></p>
  <p>RSVP Status: <%= rsvp.status %></p>
  </li>
  <% end %>
</ul>

app/views/ceremony_and_reception/info.html.erb
<% content_for :head do %>
  <script type="text/javascript"
    src="//maps.googleapis.com/maps/api/js?key=AIzaSyAvk_AVHXilZ8LOQ0XxbShiK3KmuDnMFBw&sensor=false">
  </script>
<% end %>
<div id='ceremony-and-reception'>
  <h1>Please join us from (need to confirm time) in the garden outside The International's Georgian Room, with reception to follow.</h1>
  <div id='map_canvas' style='width: 100%; height: 400px;'></div>
  <h1>The International, 81 Bay St., Brighton, Victoria, 3186</h1>
  <h1>Taxi fare from the city to the venue should cost around $30</h1>
  <h1>The ceremony will begin at 6pm. Gates will be closed once the ceremony starts, so please try to be on time.</h1>
</div>

<script type="text/javascript">
  var directionDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;
  var international = 'The International, 81 Bay St., Brighton, Victoria, 3186';
  var station = 'Southern Cross Station Docklands VIC 3008'

  function initialize() {
    directionsDisplay = new google.maps.DirectionsRenderer();
    var myOptions = {
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      center: new google.maps.LatLng(-37.90398, 144.99462)
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    directionsDisplay.setMap(map);
  }

  function calcRoute() {
    var selectedMode = 'DRIVING'
    var request = {
        origin: station ,
        destination: international,
        // Note that Javascript allows us to access the constant
        // using square brackets and a string value as its
        // "property."
        travelMode: google.maps.TravelMode[selectedMode]
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }
</script>
<% content_for :footer do %>
<script>
  $(document).ready(function() {
    initialize();
    calcRoute();
  });
</script>
<% end %>

app/views/gifts/info.html.erb
<div id='gifts'>
  <h1>As we have plenty of things for our home already, we would like you to consider the following gifts.</h1>
  <h1>A gift to charity – Our chosen charity is the <a href='https://www.redcross.org.au/Donations/onlineDonations.asp'>Red Cross.</a></h1>
  <h1>An experience</h1>
  <ul>
    <li><a href='http://www.redballoon.com.au/gift-occasions/wedding#search/?cc=au;i=1;m_products_per_page=25;q=*;q1=Gift+Occasions;q2=Wedding;q3=Victoria;sort=relevance;tp=j;x1=occ.occasionname;x2=occ.occasionvalue;x3=loc.locationname'>Red Balloon</a></li>
    <li><a href='http://www.scoopon.com.au/melbourne?gclid=CPiWwb_-orACFYhLpgod02F9Wg'>Scoopon</a></li>
    <li><a href='http://www.adrenalin.com.au/all/'>Adrenalin.com</a></li>
  </ul>
  <p>A gift of money – A wishing well will be available on the day.</p>
</div>

app/views/home/index.erb
<div id='home'>
  <h2>12.01.2013</h2>
  <div id='slideshow'>
      <%= image_tag 'home-slide1.jpg'%>
      <%= image_tag 'home-slide2.jpg'%>
      <%= image_tag 'home-slide3.jpg'%>
  </div>
  <p>The International of Brighton</p>
  <p>Georgian Room</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!-- Consider specifying the language of your content by adding the `lang` attribute to <html> -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Wedding Invite</title>
  <meta name="description" content="A wedding invitation from James and Phuong">
  <meta name="author" content="Casey Leask">

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">

  <meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1">

  <meta http-equiv="cleartype" content="on">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Great+Vibes|Stint+Ultra+Condensed' rel='stylesheet' type='text/css'>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag "modernizr" %>
  <%= csrf_meta_tags %>
  <%= yield :head if content_for?(:head) -%>
</head>
<body>
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
     chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 7]><p class="chromeframe">Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

<div id='main'>
  <h1>James & Phuong</h1>
  <div id='header'>
    <h1><%=@title %></h1>
    <ul>
      <li<%=' class=active' if current_page?(home_path)%>><%= link_to_unless_current 'Home', home_path %></li>
      <li<%=' class=active' if current_page?(ceremony_and_reception_path)%>><%= link_to_unless_current 'Ceremony And Reception', ceremony_and_reception_path %></li>
      <li<%=' class=active' if current_page?(rsvp_path) || current_page?(send_rsvp_path)%>><%= link_to_unless_current 'RSVP', rsvp_path %></li>
      <li<%=' class=active' if current_page?(gifts_path)%>><%= link_to_unless_current 'Gifts', gifts_path %></li>
      <li<%=' class=active' if current_page?(out_of_towners_path)%>><%= link_to_unless_current 'Out Of Towners', out_of_towners_path %></li>
    </ul>
    <a class='navigation'><i class='icon-chevron-down'></i></a>
  </div>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</div>

<!-- JavaScript at the bottom for fast page loading: http://developer.yahoo.com/performance/rules.html#js_bottom -->
<%= javascript_include_tag "application" %>
<%= yield :footer if content_for?(:footer) -%>
</body>
</html>

app/views/notifications/notify_rsvp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <h1>RSVP from <%= @rsvp.name -%></h1>
    <p>Number: <%= @rsvp.number -%></p>
    <p>Email: <%= @rsvp.email -%></p>
    <p>Address: <%= @rsvp.address -%></p>
    <p>Status: <%= @rsvp.status -%></p>
  </body>
</html>

app/views/notifications/notify_rsvp.text.erb
RSVP from <%= @rsvp.name %>
Number: <%= @rsvp.number %>
Email: <%= @rsvp.email %>
Address: <%= @rsvp.address %>
Status: <%= @rsvp.status %>

app/views/out_of_towners/info.html.erb
<div id='out-of-towners'>
  <h1>Accomodation</h1>
  <p><a href='https://www.google.com.au/search?q=accommodation+brighton+melbourne'>Click here</a> to search for accommodation, there are a number of hotels as well as serviced apartments in the area.</p>
  <h1>Australian Open 2013</h1>
  <p>Matches begin on January 14 th.</p>
  <h1>On sale dates - Available at Ticketek</h1>
  <h2>Single Session tickets and ground passes</h2>
  <p>On sale at 9:00 am (AEST) on Monday 10 October 2011</p>
  <h2>Series Packages</h2>
  <p>On sale from 9:00 am (AEST) Wednesday 5 October 2011 until 5:00 pm (AEST) Sunday 9 October 2011</p>
  <h1>Food</h1>
  <p>for those staying in the area or just looking for a café to pass the time, here are <a href='http://yourrestaurants.com.au/cuisine_suburb/?action=home&url_landing=vic&url_region=melbourne&url_criteria=brighton'>some suggestions.</a></p>
  <p>If you are planning to spend some time in Melbourne around our wedding date, you might want to see what’s on</p>
  <ul>
    <li><a href='http://www.victoria.aussietrueblue.com/what-to-do-in-Melbourne-January-2013.php'>What’s on in Melbourne</a></li>
    <li><a href='http://www.littlemelbourne.com.au/to-do/concerts-performances/ovo-cirque-du-soleil-melbourne-opens-17th-january-2013.html'>Cirque du Soleil</a></li>
    <li><a href='http://www.onlymelbourne.com.au/melbourne.php?id=784'>Only Melbourne (try closer to the date)</a></li>
  </ul>
</div>

app/views/rsvp/_rsvp_form.html.erb
  <%= form_for(@rsvp, :url => send_rsvp_path(@rsvp), :html => {:class => 'form_horizontal hidden'}) do |f| %>
    <%= f.hidden_field :status %>
    <%= f.label :name %>
    <%= f.text_field :name, :required => 'required' %>
    <%= f.label :number %>
    <%= f.text_field :number, :required => 'required' %>
    <%= f.label :email %>
    <%= f.text_field :email, :required => 'required' %>
    <%= f.label :address, 'Postal Address' %>
    <%= f.text_area :address, :required => 'required', :rows => 6 %>
    <%= f.submit 'Send', class: "btn btn-large btn-primary" %>
  <% end %>

app/views/rsvp/create.html.erb
<p>Thanks!</p>

app/views/rsvp/details.html.erb
<div id='rsvp'>
  <h1>Please let us know if you are available to join us on Saturday, January 12th, 2013.</h1>
  <div class='btn-group'>
    <a id='yes' href='/rsvp/yes' class='btn btn-large btn-darkgreen'>Yes</a>
    <a id='no' href='/rsvp/no' class='btn btn-large btn-darkred'>No</a>
    <a id='to-confirm' href='/rsvp/to-confirm' class='btn btn-large btn-orange'>Need to Confirm</a>
  </div>
  <%= render 'rsvp_form' %>
  <div class='clearfix'></div>
</div>
<% content_for :footer do %>
<script>
  $(document).ready(function() {
    $('.btn-group a').click(function(e) {
      $('.btn-group .selected').removeClass('selected');
      $('form.hidden').removeClass('hidden');
      $(this).addClass('selected');
      $('input#rsvp_status').attr('value', $(this).text());
      e.preventDefault();
    });
  });
</script>
<% end %>

app/views/site/home.erb
<h1>Hello World</h1>